- README.md
https://bugzilla.redhat.com/show_bug.cgi?id=1405110 is fixed in current
release.
Tested with:
ansible-2.5.5-1.el7.noarch
> Remove notes about bug in fcontext ansible module.

- README.md
- tasks/main.yml
Following PR resolves: 
https://bugzilla.redhat.com/show_bug.cgi?id=1597545
> Do not override local modifications by default

- README.md
> Include how to label ports via SELinux to README.md

- README.md
- selinux-playbook.yml
and document how to handle it. Other minor fixes to the example playbook.
> Mention that the role fails when reboot is needed

- tests/set_selinux_variables.yml
- tests/tests_boolean.yml
- tests/tests_fcontext.yml
- tests/tests_login.yml
- tests/tests_port.yml
> Test that *purge: no preserves previous state.

- defaults/main.yml
- tasks/main.yml
Signed-off-by: Major Hayden <major@redhat.com>
> Move defaults to defaults/main.yml

- tests/tests_selinux_disabled.yml
> Fix typo, older ansible did not care, but 2.7 does.

- .travis.yml
- README.md
- molecule/default/Dockerfile.j2
- molecule/default/molecule.yml
- molecule/default/yamllint.yml
Configures Molecule to do basic checks (lint/syntax, run, idempotence, Ansible check mode functionality) of the role with default parameters (tests/tests_default.yml) using Travis CI and centos6/7 docker containers.
https://travis-ci.org/linux-system-roles/selinux
> Configure Molecule and Travis CI

- .travis/runcollection.sh
- .travis/utils.sh
- library/selogin.py
- tox.ini
- Adding .travis/runcollection.sh.
- Enabling collection as part of tox/travis tests.
- Fixing a black error in library/selogin.py.
> RHELPLAN-56587 - sync collections related changes from template to selinux role

- selinux-playbook.yml
Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
> Add explaining comments to selinux-playbook.yml

- tests/selinux_test_transitions.yml
- tests/set_selinux_variables.yml
- tests/tests_all_purge.yml
- tests/tests_all_transitions.yml
- tests/tests_boolean.yml
- tests/tests_default_vars.yml
- tests/tests_fcontext.yml
- tests/tests_login.yml
- tests/tests_port.yml
- tests/tests_selinux_disabled.yml
- tests/tests_selinux_modules.yml
Some tests are problematic which cause errors in certain cases,
reboot the system, etc.  Tag these tests so the test system can
ignore them in certain cases.
Fix the wording, spelling in a couple of places.
Ensure all tasks are named.
Fix formatting in a couple of places.
> tag problematic tests; fix wording; fix formatting

- README.md
- tasks/main.yml
Code and documentation changes to support the RFE #106
> Add seuser and selevel support for selinux_fcontexts

- CHANGELOG.md
[1.5.1] - 2023-01-24
- none
- ansible-lint 6.x fixes (#132)
- Add check for non-inclusive language (#131)
- cleanup non-inclusive words.
- ensure semanage present on EL7 tests; fix jinja spacing, quoting (#139)
> Version 1.5.1 - CHANGELOG.md [citest skip]

- README.md
- library/local_semodule.py
- tasks/main.yml
- tasks/selinux_load_module.yml
- tests/tests_selinux_modules.yml
- tests/tests_selinux_modules_checksum.yml
the new implementation compares checksum of files which are supposed to be installed with checksum of already installed modules. If they match it's not necessary to install the file again.
For more details see https://github.com/linux-system-roles/selinux/issues/133
> Rewrite selinux_load_module.yml to use local_semodule 

- CHANGELOG.md
[1.5.3] - 2023-02-02
- none
- Use selinux facts to compare module checksums before copying to a node (#144)
- do not use 'become' in tests, examples (#145)
> Version 1.5.3 - CHANGELOG.md [citest skip]

- CHANGELOG.md
[1.5.4] - 2023-02-03
- none
- Fix idempotency - Use lookup file + sha256 to get hash of local policy file
- none
> Version 1.5.4 - CHANGELOG.md [citest skip]

- CHANGELOG.md
[1.5.5] - 2023-02-08
- none
- Use stat on localhost with become: false for module idempotency (#152)
- none
> Version 1.5.5 - CHANGELOG.md [citest skip]

- CHANGELOG.md
[1.5.7] - 2023-04-06
- s/restoreconf/restorecon/ (#160)
- Add README-ansible.md to refer Ansible intro page on linux-system-roles.github.io (#161)
> Version 1.5.7 - CHANGELOG.md [citest skip]

- CHANGELOG.md
Create changelog update and release for version 1.5.8
> docs(changelog): version 1.5.8 [citest skip]

- CHANGELOG.md
Create changelog update and release for version 1.6.0
> docs(changelog): version 1.6.0 [citest skip]

- .README.html
- CHANGELOG.md
Update changelog and .README.html for version 1.6.5
> docs(changelog): version 1.6.5 [citest skip]

- examples/confined_users-playbook.yml
> fix: fix ansible-lint issues

- tests/set_selinux_variables.yml
- tests/tests_modifications_with_selinux_disabled.yml
> test: skip tests_modifications_with_selinux_disabled on EL6

- CHANGELOG.md
Update changelog and .README.html for version 1.7.3
> docs(changelog): version 1.7.3 [citest skip]

- CHANGELOG.md
Update changelog and .README.html for version 1.7.4
> docs(changelog): version 1.7.4 [citest skip]

- CHANGELOG.md
Update changelog and .README.html for version 1.7.5
Signed-off-by: Sergei Petrosian <spetrosi@redhat.com>
> docs(changelog): version 1.7.5 [citest skip]

- CHANGELOG.md
Update changelog and .README.html for version 1.7.6
> docs(changelog): version 1.7.6 [citest skip]

- CHANGELOG.md
Update changelog and .README.html for version 1.7.7
> docs(changelog): version 1.7.7 [citest skip]
