linux-system-roles/selinux

- tasks/main.yml
- test/selinux.config
- test/test_selinux_disabled.yml
- vars/main.yml
When SELinux is disabled some operations like policy reload can't be
done therefore we need to:
- Change the permanent SELinux mode first
- Use '-N' option in 'semanage' import commands in order to avoid
automatic policy reloading
- Reload policy only if SELinux is not disabled
The new order of steps used in the role is:
1. Install SELinux tools
2. Set permanent SELinux mode via /etc/selinux/config
3. Set running SELinux mode - works only when SELinux is not disabled
4. Drop all local modifications - this is the place where '-N' option is added so that it works with SELinux disabled
5. Reload SELinux policy - only if SELinux is not disabled
6. Set SELinux file contexts, booleans and so on - all of them don't work with SELinux disabled due to limitations in Ansible modules
Fixes: …
> Allow setting SELinux mode when SELinux is disabled

- tasks/main.yml
- test/test_boolean.yml
- test/test_fcontext.yml
- test/test_login.yml
- test/test_port.yml
- test/test_selinux_disabled.yml
'semanage -i -' command CentOS 6 and Red Hat Enterprise Linux 6 has a
bug which resets 'noreload' global variable every time a new line is
read even when the line is empty. E.g. for
echo "fcontext -D -N\n" | semanage -i -
Since echo adds another '\n' at the end of the string it means that the
empty line at the end of the input string changes the value of
'noreload' to True and semanage tries to reload policy and it fail as
SELinux is disabled. Note: while the variable is called 'noreload' it
has the opposite meaning.
Fixes: #3
At the same time, tests are being updated to cleanup when pass and  `test_selinux_disabled` has been enhanced to cover issue #3
> Fix policy reload problem on CentOS 6 and update tests

- README.md
- selinux-playbook.yml
- tasks/main.yml
Apparently, selinux module changes the current (running) state together with the
permanent state therefore this variable seems to be pointless, see
https://bugzilla.redhat.com/show_bug.cgi?id=1602872#c0
> Drop selinux_change_running variable

- tasks/main.yml
Install python3 subpackages when python3 is used
There are python3 only systems where it's needed to install python3 SELinux userspace bindings instead of python2.
> Python3 only systems

- tasks/main.yml
If these variables are not defined, will be used current value from
Ansible facts from ansible node.
- selinux_state using ansible_selinux.config_mode
- selinux_policy using ansible_selinux.type
Resolves:
https://bugzilla.redhat.com/show_bug.cgi?id=1602897
https://bugzilla.redhat.com/show_bug.cgi?id=1602901
> Handle selinux_state and selinux_policy variables if there are not defined.

- tests/tests_boolean.yml
- tests/tests_default.yml
- tests/tests_fcontext.yml
- tests/tests_login.yml
- tests/tests_port.yml
- tests/tests_selinux_disabled.yml
selinux_*_purge variables was added, which means you need to specify
right variable to drop local modifications. This patch fixing our tests.
> Update tests for SELinux role.

- tests/tests_selinux_disabled.yml
The role nowadays fails if it finds out that the machine needs to be rebooted.
Adapt the test to this and check that the role has indeed failed and has set the correct variable.
Other minor corrections.
> Fix tests_selinux_disabled.yml

- tests/selinux_config_restore.yml
- tests/selinux_config_save.yml
- tests/tests_all_transitions.yml
tests_all_transitions.yml used to leave SELinux in a disabled state.
This was a problem if more tests are running after it, so save state at the
beginning and restore it to the original state after the test is done. This
allows all the tests to be run on a single VM, saving initializations.
> Cleanup after tests_all_transitions.yml

- tests/tests_default.yml
The idea is to run this default test with Molecule and Travis to do basic checks like in currently proposed change for timesync:
https://github.com/linux-system-roles/timesync/pull/33
> Add test running the role with default parameters

- meta/main.yml
- tasks/main.yml
- tests/selinux_apply_reboot.yml
- tests/selinux_config_restore.yml
Fixes indentation in role's metadata:
--> Executing Yamllint on files found in selinux/...
selinux/meta/main.yml
9:3       error    wrong indentation: expected 4 but found 2  (indentation)
Fixes too many spaces after colon in the 'Set SELinux file contexts' task:
selinux/tasks/main.yml
95:12     error    too many spaces after colon  (colons)
96:12     error    too many spaces after colon  (colons)
> Fix yamllint errors

- defaults/main.yml
- tasks/main.yml
- tests/tests_default_vars.yml
Those whose absence had a special meaning have a default value of null.
The second argument to the default() Jinjs2 filter was used to compensate for
the change: it causes the variable to be substituted if evaluates to false
(instead of just if undefined).
This helps using the role in Foreman/Satellite, because those introspect the
role's defaults file to know what parameters the role takes and present it to
the user. (So far, there has been no other way to declare role's input
parameters.)
> List all variables in defaults.

- .github/workflows/tox.yml
- molecule/default/molecule.yml
- tests/set_selinux_variables.yml
- tests/tests_all_purge.yml
- tests/tests_selinux_disabled.yml
Deprecate the use of molecule for linting.  Use tox for ansible-lint.
The next step will be to remove the ansible-lint dependency from
the molecule environments.
> use tox for ansible-lint instead of molecule

- meta/main.yml
- tests/selinux_apply_reboot.yml
Use the `reboot` module to restart the machine and wait for it to
come back, rather than `shell` and a separate wait task.
Change `min_ansible_version` to 2.8
> use reboot module; ansible 2.8

- library/selinux_modules_facts.py
- library/selogin.py
Adding "WARNING: Do not use this module directly! It is only for role internal use." to selogin and selinux_modules_facts module DOCUMENTATION.
Divided into 2 commits to make it easier to create a patch.
> RHELPLAN-69928  Add a note to each module Doc to indicate it is private

- tests/tests_selinux_disabled.yml
https://bugzilla.redhat.com/show_bug.cgi?id=1945359
EL9 changed the behavior with respect to mounts, so use lazy
unmount when umounting /sys/fs/selinux
It is safe to do this on all platforms.
> use lazy unmount to fix umount: target is busy

- tasks/main.yml
- tests/tests_selinux_modules.yml
Comparisons like `ansible_distribution_major_version > "7"` were broken.
Comparing number strings of different length may result in an unexpected result.
For example `"10" > "7"` evaluates to `false`.
Comparisons like `ansible_distribution_major_version | int > 7` were fine.
`... is version('7', '>')` could also be used to compare versions.
As the `... | int` conversion is used in many other places, use it for consistency.
> Fix version comparisons for ansible_distribution_major_version

- tasks/main.yml
- tasks/set_facts_packages.yml
- tests/setup-snapshot.yml
- tests/tests_default.yml
- vars/main.yml
Some users use `gather_facts: false` in their playbooks.  This changes
the role to work in that case, by gathering only the facts it requires
to run.
CI testing can be sped up by creating a snapshot image pre-installed
with packages.  tests/setup-snapshot.yml can be used by a CI system
to do this.
> support gather_facts: false; support setup-snapshot.yml (#71)

- CHANGELOG.md
[1.3.7] - 2022-07-19
- none
- none
- make all tests work with gather_facts: false (#111)
Ensure all tests work if using ANSIBLE_GATHERING=explicit
- make min_ansible_version a string in meta/main.yml (#112)
The Ansible developers say that `min_ansible_version` in meta/main.yml
must be a `string` value like `"2.9"`, not a `float` value like `2.9`.
- Add CHANGELOG.md (#113)
> Version 1.3.7 - CHANGELOG.md [citest skip]

- README.md
- library/local_seport.py
- tasks/main.yml
- tests/tests_port.yml
- `local: true`:
* `state: present` enforces change to be made even though the
port mapping could already exists in built in policy
*`state: absent` would remove only local modification and would not
try to remove builtin mapping.
Implemented using local_seport module which is copied from seport module
and update to accept `local`
> add 'local' parameter to seport

- CHANGELOG.md
[1.5.0] - 2022-09-19
- add 'local' parameter to seport (#124)
`community.general.seport` has recently added the `local` parameter
which is now supported by the role.
- `local: true`:
* `state: present` enforces change to be made even though the
port mapping could already exists in built in policy
* `state: absent` would remove only local modification and would not
try to remove builtin mapping.
The role vendors-in the seport module as `local_seport`, because otherwise
it is too difficult to support both Ansible 2.9 and ansible-core.  We will
revisit this when Ansible 2.9 is EOL.
- none
- add test for fcontext seuser and selevel (#120)
> Version 1.5.0 - CHANGELOG.md [citest skip]

- CHANGELOG.md
[1.5.2] - 2023-01-26
- none
- Rewrite selinux_load_module.yml to use local_semodule  (#135)
This makes module management idempotent on Fedora, and EL 8.6
and later.
- none
> Version 1.5.2 - CHANGELOG.md [citest skip]

- README.md
- examples/selinux-playbook.yml
- tests/tests_all_purge.yml
- tests/tests_all_transitions.yml
- tests/tests_boolean.yml
- tests/tests_fcontext.yml
- tests/tests_login.yml
- tests/tests_port.yml
- tests/tests_selinux_disabled.yml
- tests/tests_selinux_modules.yml
- tests/tests_selinux_modules_checksum.yml
The main reason is that the baseos ci test runner does not have `sudo`
installed by default, so we would need to use a different `become`
method.
But since we have to modify all of these anyway, best to just get
rid of `become`.  In general, you can't really use this role without
being root on the managed node, so it is implied.  Ansible recommends
to let the user specify `become` if necessary.  There are a variety
of ways the user can specify become:
* ansible-playbook CLI `--become` et. al.
https://docs.ansible.com/ansible/latest/cli/ansible-playbook.html
* connection variables
https://docs.ansible.com/ansible/latest/reference_appendices/special_variables.html#connection-variables
* environment variables, configuration settings …
> do not use 'become' in tests, examples

- library/selinux_modules_facts.py
- tasks/main.yml
- tasks/selinux_load_module.yml
- tests/tests_selinux_modules.yml
Should address https://github.com/linux-system-roles/selinux/issues/142
This is early development version which already supports standard cases on rhel8.-6 and later.
Even though it still needs to be finished, I'd appreciate any early feedback.
> Use selinux facts to compare module checksums before copying to a node

- tasks/selinux_load_module.yml
This is a follow up to https://github.com/linux-system-roles/selinux/issues/142
The `delegate_to: localhost`, if using `become` with the playbook, is causing
a `sudo` to `localhost`.  Use a `file` lookup through a `hash` filter to
get the checksum instead and try to bypass that delegation.
> Use lookup file + sha256 to get hash of local policy file

- CHANGELOG.md
[1.5.6] - 2023-02-09
- none
- use fileglob to lookup selinux module file - idempotency support (#155)
- none
> Version 1.5.6 - CHANGELOG.md [citest skip]

- tests/set_selinux_variables.yml
- tests/tests_selinux_modules.yml
- tests/tests_selinux_modules_checksum.yml
Ensure the tests have the facts they need when testing with
`ANSIBLE_GATHERING=explicit`, but remove them before running the
role to ensure the role will ensure the facts it needs.
> test: ensure the test works with ANSIBLE_GATHERING=explicit

- tasks/main.yml
- tests/tests_restore_dirs.yml
- vars/main.yml
From restorecon(8):
-T nthreads
use up to nthreads threads.  Specify 0 to create as many
threads as there are available CPU cores; 1 to use only a
single thread  (default); or any positive number to use
the given number of threads (if possible).
> feat: Use `restorecon -T 0` on Fedora and RHEL > 8

- tasks/main.yml
- tasks/selinux_load_module.yml
https://ansible.readthedocs.io/projects/lint/rules/var-naming/
`var-naming[no-reserved]: Variables names must not be Ansible reserved names`
Fixes this error:
```
var-naming[no-reserved]: Variables names must not be Ansible reserved names. (name)
tasks/main.yml:123
```
> refactor: ansible-lint - vars cannot be reserved names

- tasks/set_facts_packages.yml
- vars/main.yml
Cause: The comparison of the present facts with the required facts is
being done on unsorted lists.
Consequence: The comparison may fail if the only difference is the
order.  Facts are gathered unnecessarily.
Fix: Use `difference` which works no matter what the order is.  Ensure
that the fact gathering subsets used are the absolute minimum required.
Result: The role gathers only the facts it requires, and does
not unnecessarily gather facts.
> fix: facts being gathered unnecessarily

- tasks/set_facts_packages.yml
The package names `python3-libselinux` and `python3-policycoreutils`
are the actual package names.  The others are aliases - they
are `Provides:` in the RPM.  Using the actual package names makes
it easier for ostree integration as well.
> refactor: use primary package names instead of aliases

- tasks/set_facts_packages.yml
Note that Suse is unofficially supported.  The recent change for
the python3 library names made the role break on Suse.
> fix: make role work again on Suse - not officially supported

- tests/tests_modifications_with_selinux_disabled.yml
When targeted SELinux policy is installed it should be possible to setup SELinux while disabled and before it's changed to permissive/enforcing.
Related to https://github.com/linux-system-roles/selinux/issues/188
This test is supposed to fail until https://github.com/linux-system-roles/selinux/pull/194 is merged.
Enhancement:
Reason:
Result:
Issue Tracker Tickets (Jira or BZ if any):
https://github.com/linux-system-roles/selinux/issues/188
> test: Add modifications in SELinux disabled mode

- README-confined_users.md
- examples/confined_users-playbook.yml
- tasks/main.yml
Note: Relabeling user home dirs should probably be added to https://docs.ansible.com/ansible/latest/collections/community/general/selogin_module.html
> docs: Add example playbook and "readme" for confined users

- tasks/selinux_load_module.yml
Enhancement: Print an error message when module to be created doesn't exist
Reason: When specifying a non-existent file with `selinux_modules.path` the role fails with an informative message that the module file that you try to install doesn't exist.
> fix: Print an error message when module to be created doesn't exist

- .ansible-lint
- .markdownlint.yaml
- library/local_semodule.py
- tasks/main.yml
Fix yamllint issue with markdownlint config
Use FQCN for community.general modules
> ci: support ansible-lint and ansible-test 2.16

- .ansible-lint
- .github/workflows/ansible-lint.yml
- .github/workflows/ansible-managed-var-comment.yml
- .github/workflows/ansible-plugin-scan.yml
- .github/workflows/ansible-test.yml
- .github/workflows/python-unit-test.yml
The old ansible-community ansible-lint is deprecated.  There is a
new ansible-lint github action.
The latest Ansible repo gating tests run ansible-lint against
the collection format instead of against individual roles.
We have to convert the role to collection format before running
ansible-test.
This also requires tox-lsr 3.2.1 - bump other actions to use 3.2.1
Role developers can run this locally using
`tox -e collection,ansible-lint-collection`
See https://github.com/linux-system-roles/tox-lsr/pull/125
> ci: Use supported ansible-lint action; run ansible-lint against the collection

- tests/set_selinux_variables.yml
- tests/tests_fcontext.yml
Enhancement: Add python_version to test required_facts to gather ansible_python_version fact
Reason: The role didn't gather ansible_python_version but used it in tests_fcontext.yml
Result: The bug is fixed
> test: Add python_version to test facts gather ansible_python_version

- .ostree/packages-runtime-CentOS-10.txt
- .ostree/packages-runtime-RedHat-10.txt
- .ostree/packages-testing-CentOS-10.txt
- .ostree/packages-testing-RedHat-10.txt
- meta/main.yml
According to the Ansible team, support for listing platforms in
role `meta/main.yml` files is being removed.
Instead, they recommend using `galaxy_tags`
https://github.com/ansible/ansible/blob/stable-2.17/changelogs/CHANGELOG-v2.17.rst
"Remove the galaxy_info field platforms from the role templates"
https://github.com/ansible/ansible/issues/82453
Many roles already have tags such as "rhel", "redhat", "centos", and "fedora".
I propose that we ensure all of the system roles have these tags.
Some of our roles support Suse, Debian, Ubuntu, and others.
We should add tags for those e.g. the ssh role already has tags for "debian" and "ubuntu".
In addition - for each version listed under `platforms.EL` - add a tag like `elN`.
Q: Why not use a delimiter between the platform and the version e.g. …
> fix: add support for EL10

- README.md
- defaults/main.yml
- tasks/ensure_selinux_packages.yml
- vars/main.yml
Enhancement: - Added a block to identify and handle reboots for transactional update systems on package changes. Update README.
Reason: Ensure necessary reboots are managed, as changes on transactional update systems are applied in a separate snapshot and require a reboot to take effect.
Result: Manages system reboots for transactional update systems when a package is installed.
Issue Tracker Tickets (Jira or BZ if any):na
> feat: add support for transactional update

- .ostree/packages-runtime-CentOS-10.txt
- .ostree/packages-runtime-CentOS-8.txt
- .ostree/packages-runtime-CentOS-9.txt
- .ostree/packages-runtime-RedHat-10.txt
- .ostree/packages-runtime-RedHat-8.txt
- .ostree/packages-runtime-RedHat-9.txt
- README.md
- meta/collection-requirements.yml
- tasks/ensure_selinux_packages.yml
- tasks/main.yml
- tests/selinux_config_restore.yml
- tests/set_selinux_variables.yml
- tests/tests_all_transitions.yml
- vars/main.yml
Cause: On EL8 and later, the role was not setting the kernel selinux parameter when
changing the selinux state to and from disabled.
Consequence: The selinux state change was not persistent upon reboot.
Fix: Ensure that the kernel selinux parameter is correctly set when the role
changes the selinux state to and from disabled.
Result: The selinux state change to and from disabled is persistent upon reboot
on EL8 and later systems.
> fix: Set the kernel command line selinux parameter correctly when changing selinux state
